workflows:
  android-debug:
    name: Music Player A-B
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "com.example.musicplayerab"
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android APK
        script: |
          ./gradlew --no-daemon --stacktrace assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
